export const MOCK_CATEGORIES = [
  'All',
  'Digital Products & AI',
  'Performance Marketing',
  'Online Business',
];

export const MOCK_COURSES = [
  {
    id: '1',
    slug: 'create-sell-digital-product-ai',
    title: 'Create & Sell Your First Digital Product With AI',
    subtitle: 'A 3-Hour Practical Session to Take You From Idea to Your First Digital Product',
    short_description: 'A 3-Hour Practical Session to Take You From Idea to Your First Digital Product.',
    description:
      'Learn how to find the right niche, identify a real problem, create a digital product with AI, host it online, create promotional content, and launch Meta Ads.',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    instructor: 'AI Digital Product Academy',
    instructor_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    instructor_bio:
      'Digital entrepreneur & AI creator helping creators, professionals, and freelancers monetize their knowledge and launch profitable digital assets.',
    category: 'Digital Products & AI',
    price: 499,
    discounted_price: 499,
    original_price: 2499,
    rating: 4.98,
    total_ratings: 2840,
    total_students: 12500,
    total_lessons: 14,
    duration: '3 Hours',
    level: 'Beginner-Friendly',
    language: 'English / Hindi Friendly',
    certificate: true,
    last_updated: '2026-09',
    is_bestseller: true,
    is_featured: true,
    tagline: 'Practical • Beginner-Friendly • AI-Powered',
    learning_outcomes: [
      'Find your profitable niche that fits your skills, interests, and goals',
      'Identify a real problem that people actively pay to solve',
      'Use AI to generate and package high-value digital products in hours',
      'Host your product online and set up seamless automated delivery',
      'Create high-converting video and graphic promo content with AI',
      'Set up and launch high-ROI Meta Ads from scratch',
      'Scale from an MVP product into recurring digital sales',
    ],
    what_youll_learn: [
      'Find your profitable niche that fits your skills, interests, and goals',
      'Identify a real problem that people actively pay to solve',
      'Use AI to generate and package high-value digital products in hours',
      'Host your product online and set up seamless automated delivery',
      'Create high-converting video and graphic promo content with AI',
      'Set up and launch high-ROI Meta Ads from scratch',
      'Scale from an MVP product into recurring digital sales',
    ],
    requirements: [
      'No technical knowledge or coding needed',
      'No physical inventory or business setup required',
      'A computer or smartphone with an internet connection',
    ],
    modules: [
      {
        id: 'm1',
        title: 'Module 1 — Introduction to Digital Products',
        lessons: [
          { id: 'l1', title: 'Lesson 1.1 — The Power of Digital Assets & Zero Inventory Economics', description: 'This lesson introduces the fundamentals of digital products and explains how they are structured, created, and delivered to customers with zero inventory overhead.', duration: '12:30', duration_seconds: 750, is_preview: true, is_completed: true, is_locked: false },
          { id: 'l2', title: 'Lesson 1.2 — The 5-Step Formula: Problem → Solution → Package → Promote → Sell', description: 'Learn the proven 5-step framework to transform your industry knowledge into high-margin digital assets that sell on autopilot.', duration: '14:20', duration_seconds: 860, is_preview: true, is_completed: false, is_locked: false },
        ],
      },
      {
        id: 'm2',
        title: 'Module 2 — Niche Discovery',
        lessons: [
          { id: 'l3', title: 'Lesson 2.1 — Discovering Your Profitable Knowledge Niche', description: 'Step-by-step breakdown to identify underserved market gaps where customers are actively paying for actionable solutions.', duration: '15:40', duration_seconds: 940, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l4', title: 'Lesson 2.2 — AI Prompts for Market & Competitor Analysis', description: 'Leverage bespoke AI prompts to quickly extract competitor strengths, weaknesses, customer pain points, and pricing strategies.', duration: '18:15', duration_seconds: 1095, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'm3',
        title: 'Module 3 — Solve Problems with Digital Products',
        lessons: [
          { id: 'l5', title: 'Lesson 3.1 — Identifying High-Pain Urgent Problems Customers Pay For', description: 'Discover how to isolate urgent, burning problems that convert casual visitors into immediate buyers.', duration: '16:10', duration_seconds: 970, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l6', title: 'Lesson 3.2 — Structuring Your High-Value Solution & Offer', description: 'Package your knowledge into an irresistible offer structure with clear deliverables and bonuses.', duration: '14:50', duration_seconds: 890, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'm4',
        title: 'Module 4 — Create Your Digital Product with AI',
        lessons: [
          { id: 'l7', title: 'Lesson 4.1 — AI-Powered Research, Planning & Outlining SOPs', description: 'Use structured prompt workflows to plan and outline standard operating procedures, guides, and worksheets in minutes.', duration: '22:40', duration_seconds: 1360, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l8', title: 'Lesson 4.2 — Generating Ebooks, Guides, Templates & Toolkits Fast', description: 'Rapidly format, generate, and polish ready-to-sell toolkits, Notion dashboards, and downloadable templates.', duration: '25:10', duration_seconds: 1510, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'm5',
        title: 'Module 5 — Host Your Digital Product',
        lessons: [
          { id: 'l9', title: 'Lesson 5.1 — Instant Hosting & Zero-Code Landing Pages', description: 'Deploy conversion-optimized product landing pages in under 30 minutes without writing a single line of code.', duration: '17:30', duration_seconds: 1050, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l10', title: 'Lesson 5.2 — Automated Checkout, Payments & Digital File Delivery', description: 'Connect instant payment gateways with automated email receipt dispatch and direct digital asset delivery.', duration: '19:40', duration_seconds: 1180, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'm6',
        title: 'Module 6 — Create Content & Sell Your Digital Product',
        lessons: [
          { id: 'l11', title: 'Lesson 6.1 — AI Prompts for Viral Video Scripts, Hooks & Posters', description: 'Master viral short-form copywriting prompts tailored for Reels, YouTube Shorts, and high-CTR social posters.', duration: '20:15', duration_seconds: 1215, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l12', title: 'Lesson 6.2 — Organic Audience Building & Content Distribution', description: 'A systematic blueprint to build an organic following that reliably feeds targeted traffic into your sales funnel.', duration: '18:00', duration_seconds: 1080, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'm7',
        title: 'Module 7 — Set Up & Launch Meta Ads',
        lessons: [
          { id: 'l13', title: 'Lesson 7.1 — Beginner-Friendly Meta Ads Setup & Campaign Architecture', description: 'Complete walkthrough of Meta Business Manager setup, CAPI configuration, and audience targeting architecture.', duration: '24:20', duration_seconds: 1460, is_preview: false, is_completed: false, is_locked: true },
          { id: 'l14', title: 'Lesson 7.2 — Launching, Testing & Scaling Profitable ₹499 Ad Sets', description: 'Launch and scale profitable ad sets with small daily test budgets while maintaining high ROAS.', duration: '26:30', duration_seconds: 1590, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
    ],
    faqs: [
      {
        q: 'Is this suitable for beginners?',
        a: 'Yes. The session starts from the basics and takes you through the complete process step by step.',
      },
      {
        q: 'Do I need technical knowledge?',
        a: 'No. The session is designed to be beginner-friendly.',
      },
      {
        q: 'What type of digital product can I create?',
        a: 'You can create ebooks, guides, templates, checklists, workbooks, toolkits, prompt packs, courses, and other digital resources.',
      },
      {
        q: 'Will I learn how to use AI?',
        a: 'Yes. You\'ll get practical AI prompts and learn how AI can help you with niche discovery, product creation, and marketing.',
      },
      {
        q: 'Will I learn Meta Ads?',
        a: 'Yes. The session covers the basic setup and process for launching Meta Ads to promote your digital product.',
      },
      {
        q: 'How long is the session?',
        a: 'The complete session is approximately 3 hours.',
      },
      {
        q: 'How much does it cost?',
        a: 'The session is available for just ₹499 as a one-time payment.',
      },
    ],
  },
  {
    id: '2',
    slug: 'performance-marketing-meta-ads-blueprint',
    title: 'Performance Marketing & Meta Ads Scaling Blueprint',
    subtitle: 'Master Modern Meta Ad Buying, Dynamic Creative Testing, and 8-Figure Scaling Strategies',
    short_description: 'Master Modern Meta Ad Buying, Dynamic Creative Testing, and 8-Figure Scaling Strategies.',
    description: 'The definitive paid media masterclass covering Advantage+ Shopping Campaigns (ASC), 3:2:2 Dynamic Creative Testing, Server-Side CAPI tracking, post-iOS14 attribution, and vertical/horizontal budget scaling.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    instructor: 'Devon Vance',
    instructor_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    instructor_bio: 'Principal Paid Media Buyer & Growth Architect who has managed over $25M+ in profitable ad spend.',
    category: 'Performance Marketing',
    price: 1499,
    discounted_price: 1499,
    original_price: 4999,
    rating: 4.96,
    total_ratings: 1920,
    total_students: 8430,
    total_lessons: 12,
    duration: '6.5 Hours',
    level: 'Intermediate to Advanced',
    language: 'English',
    certificate: true,
    last_updated: '2026-09',
    is_bestseller: true,
    is_featured: true,
    tagline: 'High ROAS • Advantage+ • Creative Testing',
    learning_outcomes: [
      'Architect modern Advantage+ Shopping and Broad Targeting ad campaigns',
      'Deploy the 3:2:2 Dynamic Creative Testing (DCT) framework for unbeatable creative velocity',
      'Calculate exact break-even ROAS, MER (Marketing Efficiency Ratio), and contribution margin',
      'Implement server-side Meta Conversions API (CAPI) with 8.5+ Event Match Quality',
      'Scale ad accounts vertically and horizontally with automated safety rules and cost caps',
      'Brief creators and script UGC videos with >40% 3-second hook retention',
    ],
    what_youll_learn: [
      'Architect modern Advantage+ Shopping and Broad Targeting ad campaigns',
      'Deploy the 3:2:2 Dynamic Creative Testing (DCT) framework for unbeatable creative velocity',
      'Calculate exact break-even ROAS, MER (Marketing Efficiency Ratio), and contribution margin',
      'Implement server-side Meta Conversions API (CAPI) with 8.5+ Event Match Quality',
      'Scale ad accounts vertically and horizontally with automated safety rules and cost caps',
      'Brief creators and script UGC videos with >40% 3-second hook retention',
    ],
    requirements: [
      'Basic familiarity with Meta Ads Manager or eCommerce marketing',
      'An active ad account or store with intention to run paid traffic',
      'Commitment to data-driven creative testing and analytics',
    ],
    modules: [
      {
        id: 'c2_m1',
        title: 'Module 1 — Media Buying Foundations & Unit Economics',
        lessons: [
          { id: 'c2_l1', title: 'Lesson 1.1 — Modern Auction Mechanics & Algorithm Signals', description: 'Understand how Meta evaluates ad rank, estimated action rates, and user value in modern auctions.', duration: '18:45', duration_seconds: 1125, is_preview: true, is_completed: false, is_locked: false },
          { id: 'c2_l2', title: 'Lesson 1.2 — The ROAS & MER Calculator (Break-Even Math)', description: 'Master unit economics: blended MER, Net Contribution Margin, CPA tolerances, and cashflow modeling.', duration: '21:10', duration_seconds: 1270, is_preview: true, is_completed: false, is_locked: false },
          { id: 'c2_l3', title: 'Lesson 1.3 — Account Structure & Campaign Architecture', description: 'Simplify ad account architecture into testing, scaling, and retargeting tiers without audience fragmentation.', duration: '19:30', duration_seconds: 1170, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
      {
        id: 'c2_m2',
        title: 'Module 2 — Dynamic Creative Testing (DCT) Engine',
        lessons: [
          { id: 'c2_l4', title: 'Lesson 2.1 — The 3:2:2 DCT Setup & Iteration Protocol', description: 'Step-by-step setup of 3 creatives, 2 primary copies, and 2 headlines within sandbox testing ad sets.', duration: '24:00', duration_seconds: 1440, is_preview: false, is_completed: false, is_locked: true },
          { id: 'c2_l5', title: 'Lesson 2.2 — Hook Engineering & 3-Second Retention Mastery', description: 'Battle-tested hook architectures that consistently deliver above 40% thumbstop rates.', duration: '22:15', duration_seconds: 1335, is_preview: false, is_completed: false, is_locked: true },
          { id: 'c2_l6', title: 'Lesson 2.3 — UGC Briefing SOPs & Creator Negotiation', description: 'Systematic workflows to source, brief, and negotiate UGC assets with top creator talent.', duration: '20:50', duration_seconds: 1250, is_preview: false, is_completed: false, is_locked: true },
        ],
      },
    ],
    faqs: [
      {
        q: 'Is this program up-to-date with current Meta algorithm changes?',
        a: 'Yes, the entire curriculum is updated for Advantage+ Shopping Campaigns (ASC), CAPI server-side tracking, and latest creative testing methodologies.',
      },
      {
        q: 'What ad spend budget is recommended to apply these strategies?',
        a: 'You can apply these strategies starting with small test budgets (e.g. ₹500 - ₹1,000/day) up to 7-figure monthly ad spend.',
      },
    ],
  },
  {
    id: '3',
    slug: 'fullstack-ai-nextjs-python',
    title: 'Full-Stack AI Application Development with Next.js & Python',
    subtitle: 'Build & Monetize Production-Ready AI SaaS Apps with LLMs, Vector DBs, and Modern UI',
    short_description: 'Build & Monetize Production-Ready AI SaaS Apps with LLMs, Vector DBs, and Modern UI.',
    description: 'Comprehensive hands-on engineering masterclass. Learn how to architect RAG pipelines, integrate OpenAI/Anthropic models, stream AI responses with Vercel AI SDK, manage vector embeddings with pgvector/Pinecone, and implement recurring Stripe/Razorpay billing.',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    instructor: 'Marcus Chen',
    instructor_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    instructor_bio: 'Ex-Google AI Engineer, founder of two SaaS ventures. Specializes in building production LLM pipelines and Next.js platforms.',
    category: 'Online Business',
    price: 999,
    discounted_price: 999,
    original_price: 3499,
    rating: 4.95,
    total_ratings: 1140,
    total_students: 4200,
    total_lessons: 9,
    duration: '8 Hours',
    level: 'All Levels',
    language: 'English',
    certificate: true,
    last_updated: '2026-09',
    is_bestseller: false,
    is_featured: true,
    tagline: 'Production RAG • Streaming UI • SaaS Billing',
    learning_outcomes: [
      'Build full-stack AI applications with Next.js 14 App Router and FastAPI/Django backends',
      'Implement Production Retrieval-Augmented Generation (RAG) with vector embeddings',
      'Stream token-by-token AI responses using Vercel AI SDK and Server-Sent Events',
      'Set up user authentication, session security, and database schemas with PostgreSQL',
      'Integrate automated subscription billing with Razorpay and Stripe webhooks',
      'Deploy production AI workloads to Vercel and scalable cloud servers',
    ],
    what_youll_learn: [
      'Build full-stack AI applications with Next.js 14 App Router and FastAPI/Django backends',
      'Implement Production Retrieval-Augmented Generation (RAG) with vector embeddings',
      'Stream token-by-token AI responses using Vercel AI SDK and Server-Sent Events',
      'Set up user authentication, session security, and database schemas with PostgreSQL',
      'Integrate automated subscription billing with Razorpay and Stripe webhooks',
      'Deploy production AI workloads to Vercel and scalable cloud servers',
    ],
    requirements: [
      'Basic understanding of JavaScript/TypeScript and Python fundamentals',
      'A free GitHub and OpenAI/Anthropic API account',
      'Eagerness to build and ship real-world software products',
    ],
    modules: [
      {
        id: 'c3_m1',
        title: 'Module 1 — AI Architecture & LLM Fundamentals',
        lessons: [
          { id: 'c3_l1', title: 'Lesson 1.1 — High-Performance AI App Architecture', description: 'System design of modern AI applications: Frontend UI, Gateway APIs, Inference Orchestrators, and Cache layers.', duration: '20:10', duration_seconds: 1210, is_preview: true, is_completed: false, is_locked: false },
          { id: 'c3_l2', title: 'Lesson 1.2 — Prompt Engineering & Structured JSON Outputs', description: 'Mastering function calling, JSON mode, and schema guarantees.', duration: '24:30', duration_seconds: 1470, is_preview: true, is_completed: false, is_locked: false },
        ],
      },
    ],
    faqs: [
      {
        q: 'Will I get the complete source code of the project?',
        a: 'Yes! Full GitHub repository access with starter templates, production configs, and boilerplate code is included.',
      },
    ],
  },
  {
    id: '4',
    slug: 'high-ticket-client-acquisition-agency',
    title: 'Mastering High-Ticket Client Acquisition & Agency Scaling',
    subtitle: 'Systematic Cold Outreach, Inbound Funnels, and Closing $3,000–$10,000/mo Retainers',
    short_description: 'Systematic Cold Outreach, Inbound Funnels, and Closing $3,000–$10,000/mo Retainers.',
    description: 'A battle-tested agency growth blueprint. Discover how to position your high-ticket offer, build automated cold email infrastructure with AI personalization, run discovery calls that convert, and build automated fulfillment systems.',
    thumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80',
    instructor: 'Sarah Jenkins',
    instructor_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    instructor_bio: 'Scaled 3 B2B service agencies from 0 to 7-figures using systematic cold outreach and automated inbound funnels.',
    category: 'Online Business',
    price: 799,
    discounted_price: 799,
    original_price: 2999,
    rating: 4.92,
    total_ratings: 860,
    total_students: 3100,
    total_lessons: 8,
    duration: '4.5 Hours',
    level: 'Beginner to Intermediate',
    language: 'English',
    certificate: true,
    last_updated: '2026-09',
    is_bestseller: false,
    is_featured: false,
    tagline: 'Cold Email • High Ticket Sales • Agency Ops',
    learning_outcomes: [
      'Craft an irresistible high-ticket offer that sells for $3,000 - $10,000/month',
      'Set up automated multi-domain cold email engines sending 1,000+ targeted emails daily',
      'Conduct friction-free discovery calls and close clients with two-call closing frameworks',
      'Handle price objections, trust hesitation, and competition with proven scripts',
      'Build automated client onboarding workflows and standard operating procedures (SOPs)',
    ],
    what_youll_learn: [
      'Craft an irresistible high-ticket offer that sells for $3,000 - $10,000/month',
      'Set up automated multi-domain cold email engines sending 1,000+ targeted emails daily',
      'Conduct friction-free discovery calls and close clients with two-call closing frameworks',
      'Handle price objections, trust hesitation, and competition with proven scripts',
      'Build automated client onboarding workflows and standard operating procedures (SOPs)',
    ],
    requirements: [
      'A marketable skill (marketing, development, design, consulting, video editing, etc.)',
      'Basic computer and email access',
      'Commitment to taking daily action on outreach and sales pipeline management',
    ],
    modules: [
      {
        id: 'c4_m1',
        title: 'Module 1 — Offer Positioning & Market Irresistibility',
        lessons: [
          { id: 'c4_l1', title: 'Lesson 1.1 — The Grand Slam B2B Offer Architecture', description: 'How to package your service so clients perceive 10x ROI and find it irrational to say no.', duration: '19:15', duration_seconds: 1155, is_preview: true, is_completed: false, is_locked: false },
          { id: 'c4_l2', title: 'Lesson 1.2 — Pricing Psychology & Retainer Economics', description: 'Structuring value-based pricing, monthly recurring retainers, and performance bonuses.', duration: '18:40', duration_seconds: 1120, is_preview: true, is_completed: false, is_locked: false },
        ],
      },
    ],
    faqs: [
      {
        q: 'Is this program only for established agencies?',
        a: 'No, freelancers and solopreneurs looking to transition into high-ticket retainer clients will benefit tremendously.',
      },
    ],
  },
];

export const MOCK_ENROLLMENTS = [
  {
    course_id: '1',
    progress_percentage: 15,
    completed_lessons: ['l1'],
    last_watched_lesson: { id: 'l1', title: 'Lesson 1.1 — The Power of Digital Assets & Zero Inventory Economics', module_title: 'Module 1 — Introduction to Digital Products' },
    last_position_seconds: 180,
    purchased_at: '2026-09-01',
  },
];

export const MOCK_PURCHASES = [
  {
    id: 'ord_ai_digital_499',
    course_id: '1',
    course_title: 'Create & Sell Your First Digital Product With AI',
    course_thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    purchase_date: '01 Sep 2026',
    amount: 499,
    status: 'Paid',
    payment_method: 'UPI / Online Instant',
    invoice_url: '#',
  },
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Digital Creator',
  email: 'creator@digitalproduct.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
  joined: '2026-09-01',
};

export const MOCK_RECENT_ACTIVITY = [
  {
    id: 'a1',
    type: 'lesson_completed',
    title: 'Completed Lesson 1.1: The Power of Digital Assets',
    course: 'Create & Sell Your First Digital Product With AI',
    timestamp: 'Just now',
  },
];
